# Generated by Django 3.1.5 on 2021-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='timeStamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='timeStamp',
            field=models.DateTimeField(null=True),
        ),
    ]
